---
language: cpp
os: osx
osx_image: xcode9.4 # macOS 10.13
env:
  - ARCH=x86_64
  - ARCH=i386
install:
  - wget -nv https://github.com/reaper-oss/sws/raw/master/reaper/reaper_plugin.h -P vendor
  - wget -nv https://gist.github.com/cfillion/da355e8278048de08ae065d6fe6031c1/raw/reaper_plugin_functions.h -P vendor
  - git clone -q --depth 1 https://github.com/justinfrankel/WDL.git vendor/WDL

  # SWELL: optimize ListView_SetItemText on macOS
  - curl -fsSL https://github.com/cfillion/WDL/commit/a6d7f802762e5e9d9833829bab83696e0db50de6.patch | git -C vendor/WDL am
  # SWELL: disable rich text in multiline textboxes on macOS
  - curl -fsSL https://github.com/cfillion/WDL/commit/af9df173570edbb1d022045a7036d8d3296977b6.patch | git -C vendor/WDL am
script:
  - cmake -B build
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
    -DCMAKE_OSX_ARCHITECTURES="$ARCH"
    -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9
    -DCMAKE_TOOLCHAIN_FILE=cmake/brew-llvm.cmake
  - cmake --build build --target all test
addons:
  homebrew:
    packages:
      - catch2
      - cmake
      - llvm
    update: true
deploy:
  provider: releases
  name: $TRAVIS_TAG
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  draft: true
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: O7kvtWqx0hsVzWev3qzNxf9CuctG76I7dXmn4IG10AFkKmot+QT9V1OARqLhOLj/QSuPWQY7X/hSPuSLqcRTweADWfOl7uKvBd38KKfEXSVfRNRgDzCTOKYmCUAzL3WFB5wGTWIP47/4GPAiqhtLriejbbMCcF6b4diZ3rD4rZN/4BI85wXh3mID0fD4i2cSzAx2ONn4I3xIAiRhigJQ0VRp3v4wMGB0hGPM3fRDMzDuGEMo3CAgyhO/ldh9QPOS4F5LNOM3prBSYmFaARQO46vmhF4hI+ydRZrntGhL5NryEtsZVqONv+Pq6z8TnCOH7uPYE9uHiU3K/s4XpYRdSMbrZfRylmTEo8p66KLjfDvMlMBmwmvsTIE8z/w9XuUskhSSq7eNYyX1QxaIiBh+o0ho/FIbLuEZK56dFCO/6yUY9LC23/+iMdPluMdQNzTPjvVqI1AnZQeBqQ2hZG9jp96Rblptz3lJFMDo3hoGNbPHE6iiCW7S0RvncGIRt5JL8BuQwyowIKqBg4eEx+74aYX7JvVLQpfzw9btr6f56k9N7OFP2tU2eNEnOWTjmkqsicU3nAp1Zji66+ncOhfJTJSIc5xNJGmVfRBSIAMYcjfo+1sxoM0NYyODXrwVt5rMUGdmuIutC7K8IcuCIOBTG924exXpBAcCYUaXd2iewss=
  file: build/reaper_reapack*.dylib
  file_glob: true
  on:
    tags: true
